### ISSUE TITLE
how to fix this 

### ISSUE THREAD

**Issue by standby312** [roxakasura/emulator-season6-update10#1]
\test\sourceS6\GameServer\GameServer\Util.cpp(654,2): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\random(1210,14): error C2039: 'generate': is not a member of 'std::random_device'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\random(5040): message : see declaration of 'std::random_device'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\random(1199): message : see reference to function template instantiation 'void std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253>::seed<_Seed_seq,0>(_Seed_seq &)' being compiled
1>        with
1>        [
1>            _Seed_seq=std::random_device
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\random(1199): message : see reference to function template instantiation 'void std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253>::seed<_Seed_seq,0>(_Seed_seq &)' being compiled
1>        with
1>        [
1>            _Seed_seq=std::random_device
1>        ]
1>D:\test\sourceS6\GameServer\GameServer\Util.cpp(600): message : see reference to function template instantiation 'std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253>::mersenne_twister_engine<std::random_device,0>(_Seed_seq &)' being compiled
1>        with
1>        [
1>            _Seed_seq=std::random_device
1>        ]
1>D:\test\sourceS6\GameServer\GameServer\Util.cpp(600): message : see reference to function template instantiation 'std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253>::mersenne_twister_engine<std::random_device,0>(_Seed_seq &)' being compiled
1>        with
1>        [
1>            _Seed_seq=std::random_device
1>        ]

https://imgur.com/ntuPxjs

**Comment by roxakasura** [comment]
i'm not a support.
